/**
 * PDF formatter — renders a `ScanResult` (and optional `FixResult`) as a PDF
 * report using pdfkit. Writes synchronously to the given output path.
 */

import PDFDocument from 'pdfkit';
import * as fs from 'node:fs';
import type {
  ScanResult,
  FixResult,
  DependencyIssue,
  ImportIssue,
  VariableIssue,
  SecurityIssue,
  EnvIssue,
  SecuritySeverity,
} from '../types.js';

// ─── Colour palette ──────────────────────────────────────────────────────────

const COLORS = {
  primary:   '#1E3A5F',
  accent:    '#2E86AB',
  success:   '#27AE60',
  warning:   '#E67E22',
  danger:    '#E74C3C',
  critical:  '#8B0000',
  muted:     '#7F8C8D',
  lightGray: '#ECF0F1',
  darkGray:  '#2C3E50',
  white:     '#FFFFFF',
  black:     '#1A1A1A',
};

const SEVERITY_COLOR: Record<SecuritySeverity, string> = {
  critical: COLORS.critical,
  high:     COLORS.danger,
  moderate: COLORS.warning,
  low:      COLORS.success,
  info:     COLORS.accent,
};


// ─── Layout constants ────────────────────────────────────────────────────────

const PAGE_WIDTH  = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const MARGIN      = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function truncate(text: string, max: number): string {
  return text.length > max ? text.slice(0, max - 1) + '…' : text;
}

function secSeverityLabel(sev: SecuritySeverity): string {
  return sev.charAt(0).toUpperCase() + sev.slice(1);
}

function drawHRule(doc: PDFKit.PDFDocument, y: number, color = COLORS.lightGray): void {
  doc.save()
     .strokeColor(color)
     .lineWidth(0.5)
     .moveTo(MARGIN, y)
     .lineTo(PAGE_WIDTH - MARGIN, y)
     .stroke()
     .restore();
}

// ─── Page header / footer ─────────────────────────────────────────────────────

function addHeader(doc: PDFKit.PDFDocument, title: string): void {
  doc.save()
     .rect(0, 0, PAGE_WIDTH, 54)
     .fill(COLORS.primary)
     .fillColor(COLORS.white)
     .fontSize(18).font('Helvetica-Bold')
     .text('depdoctor', MARGIN, 16, { lineBreak: false })
     .fontSize(10).font('Helvetica')
     .text(title, MARGIN, 38, { lineBreak: false })
     .restore();
}

function addFooter(doc: PDFKit.PDFDocument, pageNum: number, total: number): void {
  const y = PAGE_HEIGHT - 26;
  drawHRule(doc, y);
  doc.save()
     .fillColor(COLORS.muted)
     .fontSize(8).font('Helvetica')
     .text(
       `Generated by depdoctor on ${new Date().toUTCString()}`,
       MARGIN, y + 6,
       { lineBreak: false },
     )
     .text(
       `Page ${pageNum} of ${total}`,
       0, y + 6,
       { align: 'right', width: PAGE_WIDTH - MARGIN },
     )
     .restore();
}

// ─── Summary cards ────────────────────────────────────────────────────────────

interface CardData { label: string; value: number; color: string }

function drawSummaryCards(doc: PDFKit.PDFDocument, y: number, cards: CardData[]): number {
  const cardW = 95;
  const cardH = 54;
  const gap   = 10;
  const startX = MARGIN;

  for (let i = 0; i < cards.length; i++) {
    const cx = startX + i * (cardW + gap);
    const card = cards[i];
    if (!card) continue;

    doc.save()
       .roundedRect(cx, y, cardW, cardH, 6)
       .fill(card.color)
       .fillColor(COLORS.white)
       .fontSize(22).font('Helvetica-Bold')
       .text(String(card.value), cx, y + 8, { width: cardW, align: 'center', lineBreak: false })
       .fontSize(8).font('Helvetica')
       .text(card.label, cx, y + 34, { width: cardW, align: 'center', lineBreak: false })
       .restore();
  }

  return y + cardH + 18;
}

// ─── Section header ───────────────────────────────────────────────────────────

function drawSectionHeader(doc: PDFKit.PDFDocument, y: number, title: string, count: number): number {
  doc.save()
     .rect(MARGIN, y, CONTENT_WIDTH, 22)
     .fill(COLORS.primary)
     .fillColor(COLORS.white)
     .fontSize(10).font('Helvetica-Bold')
     .text(`${title}  (${count})`, MARGIN + 8, y + 6, { lineBreak: false })
     .restore();
  return y + 22 + 8;
}

// ─── Table helpers ────────────────────────────────────────────────────────────

interface ColumnDef { header: string; width: number }

function drawTableHeader(
  doc: PDFKit.PDFDocument,
  y: number,
  columns: ColumnDef[],
): number {
  doc.save()
     .rect(MARGIN, y, CONTENT_WIDTH, 16)
     .fill(COLORS.darkGray)
     .fillColor(COLORS.white)
     .fontSize(7.5).font('Helvetica-Bold');

  let x = MARGIN + 4;
  for (const col of columns) {
    doc.text(col.header, x, y + 4, { width: col.width - 4, lineBreak: false });
    x += col.width;
  }

  doc.restore();
  return y + 16;
}

function drawTableRow(
  doc: PDFKit.PDFDocument,
  y: number,
  columns: ColumnDef[],
  cells: string[],
  rowIndex: number,
  rowHeight = 14,
): number {
  const bg = rowIndex % 2 === 0 ? COLORS.white : COLORS.lightGray;
  doc.save()
     .rect(MARGIN, y, CONTENT_WIDTH, rowHeight)
     .fill(bg)
     .fillColor(COLORS.black)
     .fontSize(7).font('Helvetica');

  let x = MARGIN + 4;
  for (let i = 0; i < columns.length; i++) {
    const col = columns[i];
    const cell = cells[i] ?? '';
    if (!col) { continue; }
    doc.text(truncate(cell, 80), x, y + 3, { width: col.width - 4, lineBreak: false });
    x += col.width;
  }

  doc.restore();
  return y + rowHeight;
}

// ─── Page management ──────────────────────────────────────────────────────────

class PagedPDF {
  doc: PDFKit.PDFDocument;
  private pageCount = 1;
  private title: string;
  y: number;

  constructor(title: string) {
    this.title = title;
    this.doc = new PDFDocument({ size: 'A4', margin: 0, autoFirstPage: false, bufferPages: true });
    this.y = 0;
    this.newPage();
  }

  newPage(): void {
    this.doc.addPage();
    this.pageCount++;
    addHeader(this.doc, this.title);
    this.y = 72; // below header
  }

  ensureSpace(needed: number): void {
    if (this.y + needed > PAGE_HEIGHT - 46) {
      this.newPage();
    }
  }

  finalize(): void {
    const range = this.doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      this.doc.switchToPage(range.start + i);
      addFooter(this.doc, range.start + i + 1, range.count);
    }
    this.doc.flushPages();
  }

  pipe(stream: fs.WriteStream): void {
    this.doc.pipe(stream);
  }

  end(): void {
    this.doc.end();
  }
}

// ─── Section renderers ────────────────────────────────────────────────────────

function renderDependencySection(pdf: PagedPDF, issues: DependencyIssue[]): void {
  if (issues.length === 0) return;
  pdf.ensureSpace(50);
  pdf.y = drawSectionHeader(pdf.doc, pdf.y, 'Unused Dependencies', issues.length);

  const cols: ColumnDef[] = [
    { header: 'Package',     width: 160 },
    { header: 'Type',        width: 90  },
    { header: 'Severity',    width: 65  },
    { header: 'Description', width: CONTENT_WIDTH - 315 },
  ];

  pdf.ensureSpace(16);
  pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

  for (let i = 0; i < issues.length; i++) {
    pdf.ensureSpace(14);
    const issue = issues[i];
    if (!issue) continue;
    pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
      issue.name,
      issue.type,
      issue.severity,
      issue.description,
    ], i);
  }

  pdf.y += 12;
}

function renderImportSection(pdf: PagedPDF, issues: ImportIssue[]): void {
  if (issues.length === 0) return;
  pdf.ensureSpace(50);
  pdf.y = drawSectionHeader(pdf.doc, pdf.y, 'Unused Imports', issues.length);

  const cols: ColumnDef[] = [
    { header: 'File',      width: 180 },
    { header: 'Line',      width: 40  },
    { header: 'Source',    width: 130 },
    { header: 'Specifier', width: 100 },
    { header: 'Severity',  width: CONTENT_WIDTH - 450 },
  ];

  pdf.ensureSpace(16);
  pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

  for (let i = 0; i < issues.length; i++) {
    pdf.ensureSpace(14);
    const issue = issues[i];
    if (!issue) continue;
    pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
      issue.file,
      String(issue.line),
      issue.source,
      issue.specifier ?? '—',
      issue.severity,
    ], i);
  }

  pdf.y += 12;
}

function renderVariableSection(pdf: PagedPDF, issues: VariableIssue[]): void {
  if (issues.length === 0) return;
  pdf.ensureSpace(50);
  pdf.y = drawSectionHeader(pdf.doc, pdf.y, 'Unused Variables', issues.length);

  const cols: ColumnDef[] = [
    { header: 'File',        width: 200 },
    { header: 'Line',        width: 40  },
    { header: 'Name',        width: 120 },
    { header: 'Kind',        width: 50  },
    { header: 'Severity',    width: CONTENT_WIDTH - 410 },
  ];

  pdf.ensureSpace(16);
  pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

  for (let i = 0; i < issues.length; i++) {
    pdf.ensureSpace(14);
    const issue = issues[i];
    if (!issue) continue;
    pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
      issue.file,
      String(issue.line),
      issue.name,
      issue.kind,
      issue.severity,
    ], i);
  }

  pdf.y += 12;
}

function renderSecuritySection(pdf: PagedPDF, issues: SecurityIssue[]): void {
  if (issues.length === 0) return;
  pdf.ensureSpace(50);
  pdf.y = drawSectionHeader(pdf.doc, pdf.y, 'Security Issues', issues.length);

  const order: SecuritySeverity[] = ['critical', 'high', 'moderate', 'low', 'info'];
  const grouped = new Map<SecuritySeverity, SecurityIssue[]>();
  for (const sev of order) grouped.set(sev, []);
  for (const issue of issues) grouped.get(issue.severity)?.push(issue);

  for (const sev of order) {
    const group = grouped.get(sev) ?? [];
    if (group.length === 0) continue;

    pdf.ensureSpace(20);
    const color = SEVERITY_COLOR[sev];
    pdf.doc.save()
       .rect(MARGIN, pdf.y, CONTENT_WIDTH, 16)
       .fill(color)
       .fillColor(COLORS.white)
       .fontSize(8).font('Helvetica-Bold')
       .text(`${secSeverityLabel(sev)} (${group.length})`, MARGIN + 8, pdf.y + 4, { lineBreak: false })
       .restore();
    pdf.y += 16;

    const cols: ColumnDef[] = [
      { header: 'Package',        width: 130 },
      { header: 'Type',           width: 90  },
      { header: 'Description',    width: 220 },
      { header: 'Recommendation', width: CONTENT_WIDTH - 440 },
    ];

    pdf.ensureSpace(16);
    pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

    for (let i = 0; i < group.length; i++) {
      pdf.ensureSpace(14);
      const issue = group[i];
      if (!issue) continue;
      pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
        issue.package,
        issue.type,
        issue.description,
        issue.recommendation ?? '—',
      ], i);
    }

    pdf.y += 8;
  }

  pdf.y += 4;
}

function renderEnvSection(pdf: PagedPDF, issues: EnvIssue[]): void {
  if (issues.length === 0) return;
  pdf.ensureSpace(50);
  pdf.y = drawSectionHeader(pdf.doc, pdf.y, 'Environment Variable Issues', issues.length);

  const cols: ColumnDef[] = [
    { header: 'Variable',    width: 130 },
    { header: 'File',        width: 150 },
    { header: 'Line',        width: 40  },
    { header: 'Type',        width: 80  },
    { header: 'Severity',    width: 60  },
    { header: 'Description', width: CONTENT_WIDTH - 460 },
  ];

  pdf.ensureSpace(16);
  pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

  for (let i = 0; i < issues.length; i++) {
    pdf.ensureSpace(14);
    const issue = issues[i];
    if (!issue) continue;
    pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
      issue.variable,
      issue.file,
      String(issue.line),
      issue.type,
      issue.severity,
      issue.description,
    ], i);
  }

  pdf.y += 12;
}

function renderFixSection(pdf: PagedPDF, fixResult: FixResult): void {
  pdf.ensureSpace(50);
  pdf.y = drawSectionHeader(
    pdf.doc,
    pdf.y,
    'Fix Results',
    fixResult.applied.length + fixResult.skipped.length,
  );

  // Applied fixes
  if (fixResult.applied.length > 0) {
    pdf.ensureSpace(20);
    pdf.doc.save()
       .fillColor(COLORS.success)
       .fontSize(9).font('Helvetica-Bold')
       .text(`✓ Applied (${fixResult.applied.length})`, MARGIN + 4, pdf.y, { lineBreak: false })
       .restore();
    pdf.y += 16;

    const cols: ColumnDef[] = [
      { header: 'Type',        width: 110 },
      { header: 'File',        width: 180 },
      { header: 'Description', width: CONTENT_WIDTH - 290 },
    ];
    pdf.ensureSpace(16);
    pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

    for (let i = 0; i < fixResult.applied.length; i++) {
      pdf.ensureSpace(14);
      const action = fixResult.applied[i];
      if (!action) continue;
      pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
        action.type,
        action.file ?? '—',
        action.description,
      ], i);
    }
    pdf.y += 10;
  }

  // Skipped fixes
  if (fixResult.skipped.length > 0) {
    pdf.ensureSpace(20);
    pdf.doc.save()
       .fillColor(COLORS.muted)
       .fontSize(9).font('Helvetica-Bold')
       .text(`⤷ Skipped (${fixResult.skipped.length})`, MARGIN + 4, pdf.y, { lineBreak: false })
       .restore();
    pdf.y += 16;

    const cols: ColumnDef[] = [
      { header: 'Type',        width: 110 },
      { header: 'File',        width: 180 },
      { header: 'Description', width: CONTENT_WIDTH - 290 },
    ];
    pdf.ensureSpace(16);
    pdf.y = drawTableHeader(pdf.doc, pdf.y, cols);

    for (let i = 0; i < fixResult.skipped.length; i++) {
      pdf.ensureSpace(14);
      const action = fixResult.skipped[i];
      if (!action) continue;
      pdf.y = drawTableRow(pdf.doc, pdf.y, cols, [
        action.type,
        action.file ?? '—',
        action.description,
      ], i);
    }
    pdf.y += 10;
  }

  // Errors
  if (fixResult.errors.length > 0) {
    pdf.ensureSpace(20);
    pdf.doc.save()
       .fillColor(COLORS.danger)
       .fontSize(9).font('Helvetica-Bold')
       .text(`✗ Errors (${fixResult.errors.length})`, MARGIN + 4, pdf.y, { lineBreak: false })
       .restore();
    pdf.y += 14;

    for (const errMsg of fixResult.errors) {
      pdf.ensureSpace(12);
      pdf.doc.save()
         .fillColor(COLORS.danger)
         .fontSize(7.5).font('Helvetica')
         .text(`• ${errMsg}`, MARGIN + 8, pdf.y, { width: CONTENT_WIDTH - 16, lineBreak: false })
         .restore();
      pdf.y += 12;
    }
  }

  if (fixResult.backupPath !== null) {
    pdf.ensureSpace(14);
    pdf.doc.save()
       .fillColor(COLORS.muted)
       .fontSize(7.5).font('Helvetica')
       .text(`Backup: ${fixResult.backupPath}`, MARGIN + 4, pdf.y, { lineBreak: false })
       .restore();
    pdf.y += 14;
  }
}

// ─── Cover / metadata block ───────────────────────────────────────────────────

function renderMeta(pdf: PagedPDF, result: ScanResult): void {
  const totalIssues =
    result.dependencyIssues.length +
    result.importIssues.length +
    result.variableIssues.length +
    result.securityIssues.length +
    result.envIssues.length;

  // Status line
  const statusBg = totalIssues === 0 ? COLORS.success : COLORS.warning;
  const statusText =
    totalIssues === 0
      ? 'No issues found'
      : `${totalIssues} issue(s) found`;

  pdf.doc.save()
     .roundedRect(MARGIN, pdf.y, CONTENT_WIDTH, 26, 5)
     .fill(statusBg)
     .fillColor(COLORS.white)
     .fontSize(12).font('Helvetica-Bold')
     .text(statusText, MARGIN, pdf.y + 7, { width: CONTENT_WIDTH, align: 'center', lineBreak: false })
     .restore();
  pdf.y += 34;

  // Meta row
  pdf.doc.save()
     .fillColor(COLORS.muted)
     .fontSize(8).font('Helvetica')
     .text(`Project: ${result.projectRoot}`, MARGIN, pdf.y)
     .text(`Scanned: ${result.filesScanned} file(s) in ${result.durationMs}ms`, MARGIN, pdf.y + 12)
     .text(`Date: ${new Date().toUTCString()}`, MARGIN, pdf.y + 24)
     .restore();
  pdf.y += 42;

  // Summary cards
  const cards: CardData[] = [
    { label: 'Unused Deps',   value: result.dependencyIssues.length, color: COLORS.accent   },
    { label: 'Unused Imports',value: result.importIssues.length,     color: COLORS.primary  },
    { label: 'Unused Vars',   value: result.variableIssues.length,   color: COLORS.darkGray },
    { label: 'Security',      value: result.securityIssues.length,   color: COLORS.danger   },
    { label: 'Env Issues',    value: result.envIssues.length,        color: COLORS.warning  },
  ];
  pdf.y = drawSummaryCards(pdf.doc, pdf.y, cards);

  drawHRule(pdf.doc, pdf.y);
  pdf.y += 12;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate a PDF scan report and write it to `outputPath`.
 * Returns a Promise that resolves when the file is fully written.
 */
export function generatePdfReport(
  result: ScanResult,
  outputPath: string,
  fixResult?: FixResult,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const title = fixResult !== undefined ? 'Fix Report' : 'Scan Report';
    const pdf = new PagedPDF(title);
    const stream = fs.createWriteStream(outputPath);

    stream.on('error', reject);
    stream.on('finish', resolve);

    pdf.pipe(stream);

    renderMeta(pdf, result);
    renderDependencySection(pdf, result.dependencyIssues);
    renderImportSection(pdf, result.importIssues);
    renderVariableSection(pdf, result.variableIssues);
    renderSecuritySection(pdf, result.securityIssues);
    renderEnvSection(pdf, result.envIssues);

    if (fixResult !== undefined) {
      renderFixSection(pdf, fixResult);
    }

    pdf.finalize();
    pdf.end();
  });
}
